# Generated by Django 2.2.16 on 2022-03-11 00:59

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionDescription', models.TextField(default='', null=True)),
                ('exerId', models.CharField(max_length=50, unique=True)),
                ('exercise', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('name', models.CharField(max_length=155)),
                ('thumbnailUrl', models.URLField(null=True)),
                ('versions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
