# Generated by Django 2.2.16 on 2022-03-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movements',
            name='past_id',
        ),
    ]
