# Generated by Django 2.2.16 on 2022-03-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Exercise'),
        ),
    ]
