# Generated by Django 2.2.16 on 2022-03-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='created_at',
        ),
    ]
