# Generated by Django 2.2.16 on 2022-03-08 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movements_past_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
