services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: /backend/entrypoint.sh
    volumes:
      - ./backend:/backend
      - /backend/venv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=True
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
      - WATCHPACK_POLLING=true
      - REACT_APP_BASE_BE_URL=http://localhost:8000
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:
