databases:
  - name: exerai-db
    plan: free
    region: oregon

services:
  # Django Backend API
  - type: web
    name: exerai-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: exerai-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://exerai-frontend.onrender.com"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true

  # React Frontend
  - type: web
    name: exerai-frontend
    runtime: static
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/build"
    envVars:
      - key: REACT_APP_BASE_BE_URL
        value: https://exerai-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
