services:
  # PostgreSQL Database
  - type: pserv
    name: exerai-db
    env: postgresql
    plan: free

  # Django Backend API
  - type: web
    name: exerai-backend
    env: docker
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python manage.py migrate
      python manage.py loaddata api/fixtures/movements.json || true
      python manage.py loaddata api/fixtures/exercises.json || true
      gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: POSTGRES_DB
        fromDatabase:
          name: exerai-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: exerai-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: exerai-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: exerai-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: exerai-db
          property: port
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://exerai-frontend.onrender.com"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true

  # React Frontend
  - type: web
    name: exerai-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BASE_BE_URL
        value: https://exerai-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
